### PR TITLE
Feature mission leave action

### PR DESCRIPTION
**Pull request by gtekle**
## What this PR does: (Issue #9 )
  - Added action creator function for `Leave Mission` action and updated `missionsReducer`
  -  Added logic to dispatch `Leave Mission` action when a user clicks the "Leave Mission" button

## To test it
  - Install Node ^14.0
  - clone the repository by running\
      `git clone https://github.com/AdornChoga/space_travelers_hub.git`
  - navigate to the folder\
      `cd space_travelers_hub`
  - Install packages\
      `npm install`
  - run the application\
      `npm start`
  - Look for the `redux logger` output in Chrome Dev Tools console

### CODE REVIEW

**Review by AdornChoga — CHANGES_REQUESTED** [review]
Hi @gtekle 

Good job on implementing the leave-mission feature. There is one change that needs to be done before merging the feature.
You are almost there. 😃 

*Required Changes*

- Let's not have two buttons for the join-mission and leave-mission functionalities, instead let's change the text of the same button based on the state of the mission. Check out [this example](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/images/space-travelers__missions.png) in the wireframe.

**Comment by gtekle** [comment]
Hi @AdornChoga 
Thank you for the feedback. The two buttons are necessary for the next issue which is conditional component rendering. 

> 
>  {rocket.reserved && ( 
>     // render Cancel Rocket button
> )}

**Comment by AdornChoga** [comment]
Pardon me, my bad for not paying attention to that detail in the Kanban board. I will go ahead and approve your pull request right away.

**Comment by gtekle** [comment]
Thanks! :+1: :+1:

**Review by AdornChoga — APPROVED** [review]
Congratulations on implementing the leave-mission feature exactly as required in the kanban board task. This feature is ready to be merged. 🏃 

Cheers and Happy coding. 🥳

**Comment by gtekle** [comment]
:+1:

**Pull request merged**
